name: QA API AUTOMATION - TrackSTG1

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out QA Automation Code
      uses: actions/checkout@v3
      with:
        repository: travelnetsolutions/qa-api-automation
        path: qa-api-automation

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install Maven
      run: sudo apt-get install maven -y

    - name: Replace placeholders in authentication.json for TrackSTG1
      run: |
        # Handle projectUrl
        if [ -n "${{ secrets.TRACKSTG1_PROJECT_URL }}" ]; then
          sed -i '/"TrackSTG1": {/,/}/ s#"<Url>"#${{ secrets.TRACKSTG1_PROJECT_URL }}#g' qa-api-automation/src/test/resources/authentication.json
        else
          sed -i '/"TrackSTG1": {/,/}/ s#.*"projectUrl": ".*",##g' qa-api-automation/src/test/resources/authentication.json
        fi

        # Handle apiKey
        if [ -n "${{ secrets.TRACKSTG1_API_KEY }}" ]; then
          sed -i '/"TrackSTG1": {/,/}/ s#"<Key>"#${{ secrets.TRACKSTG1_API_KEY }}#g' qa-api-automation/src/test/resources/authentication.json
        else
          sed -i '/"TrackSTG1": {/,/}/ s#.*"apiKey": ".*",##g' qa-api-automation/src/test/resources/authentication.json
        fi

        # Handle apiSecret
        if [ -n "${{ secrets.TRACKSTG1_API_SECRET }}" ]; then
          sed -i '/"TrackSTG1": {/,/}/ s#"<Secret>"#${{ secrets.TRACKSTG1_API_SECRET }}#g' qa-api-automation/src/test/resources/authentication.json
        else
          sed -i '/"TrackSTG1": {/,/}/ s#.*"apiSecret": ".*",##g' qa-api-automation/src/test/resources/authentication.json
        fi

        # Handle dbUrl
        if [ -n "${{ secrets.TRACKSTG1_DB_URL }}" ]; then
          sed -i '/"TrackSTG1": {/,/}/ s#"<dbUrl>"#${{ secrets.TRACKSTG1_DB_URL }}#g' qa-api-automation/src/test/resources/authentication.json
        else
          sed -i '/"TrackSTG1": {/,/}/ s#.*"dbUrl": ".*",##g' qa-api-automation/src/test/resources/authentication.json
        fi

        # Handle dbName
        if [ -n "${{ secrets.TRACKSTG1_DB_NAME }}" ]; then
          sed -i '/"TrackSTG1": {/,/}/ s#"<dbName>"#${{ secrets.TRACKSTG1_DB_NAME }}#g' qa-api-automation/src/test/resources/authentication.json
        else
          sed -i '/"TrackSTG1": {/,/}/ s#.*"dbName": ".*",##g' qa-api-automation/src/test/resources/authentication.json
        fi

        # Handle dbUsername
        if [ -n "${{ secrets.TRACKSTG1_DB_USERNAME }}" ]; then
          sed -i '/"TrackSTG1": {/,/}/ s#"<dbUsername>"#${{ secrets.TRACKSTG1_DB_USERNAME }}#g' qa-api-automation/src/test/resources/authentication.json
        else
          sed -i '/"TrackSTG1": {/,/}/ s#.*"dbUsername": ".*",##g' qa-api-automation/src/test/resources/authentication.json
        fi

        # Handle dbPassword
        if [ -n "${{ secrets.TRACKSTG1_DB_PASSWORD }}" ]; then
          sed -i '/"TrackSTG1": {/,/}/ s#"<dbPassword>"#${{ secrets.TRACKSTG1_DB_PASSWORD }}#g' qa-api-automation/src/test/resources/authentication.json
        else
          sed -i '/"TrackSTG1": {/,/}/ s#.*"dbPassword": ".*"##g' qa-api-automation/src/test/resources/authentication.json
        fi

    - name: Run Karate Tests
      run: mvn clean test -Dkarate.env=TrackSTG1 -f qa-api-automation/pom.xml
